server:
  port: 8001
#  servlet:
#    context-path: /api
spring:

  cloud:
   consul:
     host: consul.hongkun.com.cn
     port: 80
     enabled: true
     discovery:
       register: false

  datasource:
    druid:
      # Druid 监控 Servlet 配置参数
      druidRegistrationUrl: /druid/*
      resetEnable: true
      loginUsername: admin
      loginPassword: admin
      # Druid 监控过滤相关配置参数
      filtersUrlPatterns: /*
      exclusions: '*.js,*.gif,*.jpg,*.jpeg,*.png,*.css,*.ico,*.jsp,/druid/*,/swagger-*,/v2/*,/webjars/*'
      sessionStatMaxCount: 2000
      sessionStatEnable: true
      principalSessionName: session_user_key
      profileEnable: true

      hxopensys:
        url: jdbc:mysql://192.168.0.34:3306/opensys?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=CTT
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: msbu@)!%0225
        filters: stat,wall
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: false
        maxPoolPreparedStatementPerConnectionSize: 0
        removeAbandoned: true
        removeAbandonedTimeoutMillis: 20000
        logAbandoned: true
        logDifferentThread: true
        connectionProperties:  druid.stat.mergeSql=true;druid.stat.logSlowSql=true;druid.stat.slowSqlMillis=3000
        useGlobalDataSourceStat: true

      hxgol:
        url: jdbc:mysql://192.168.0.34:3306/3gol?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=CTT
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: msbu@)!%0225
        filters: stat,wall
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: false
        maxPoolPreparedStatementPerConnectionSize: 0
        removeAbandoned: true
        removeAbandonedTimeoutMillis: 20000
        logAbandoned: true
        logDifferentThread: true
        connectionProperties:  druid.stat.mergeSql=true;druid.stat.logSlowSql=true;druid.stat.slowSqlMillis=3000
        useGlobalDataSourceStat: true

      apply:
        url: jdbc:mysql://shared-mysql.hongkun.com.cn:6033/admin_platform?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=CTT
        driver-class-name: com.mysql.jdbc.Driver
        username: hkdc_app_user
        password: pwdn40NeezOLgvZ
        filters: stat,wall
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: false
        maxPoolPreparedStatementPerConnectionSize: 0
        removeAbandoned: true
        removeAbandonedTimeoutMillis: 20000
        logAbandoned: true
        logDifferentThread: true
        connectionProperties:  druid.stat.mergeSql=true;druid.stat.logSlowSql=true;druid.stat.slowSqlMillis=3000
        useGlobalDataSourceStat: true

      mapproval:
        url: jdbc:mysql://shared-mysql.hongkun.com.cn:6033/mapproval?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=CTT
        driver-class-name: com.mysql.jdbc.Driver
        username: mapproval_user
        password: tR6FTQvRyX9Li4i
        filters: stat,wall
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: false
        maxPoolPreparedStatementPerConnectionSize: 0
        removeAbandoned: true
        removeAbandonedTimeoutMillis: 20000
        logAbandoned: true
        logDifferentThread: true
        connectionProperties:  druid.stat.mergeSql=true;druid.stat.logSlowSql=true;druid.stat.slowSqlMillis=3000
        useGlobalDataSourceStat: true

  #############redis配置
  redis:
    database: 0
    host: redis
    port: 6379
    jedis:
      pool:
        max-idle: 8
        max-active: 9000
        max-wait: 6000ms
        min-idle: 5
    timeout: 6000ms


#鸿信monggod地址
mongoDBPort: 27017
mongoDBUrl: 192.168.0.34


config:
  hx:
    orgInfoId: 71e96ed0-9934-11e7-beda-0050569f596d
    tsqUrl: http://tsq.hongkun.com.cn
    #文件上传路径
    filePath: /data/hxdata/codeData/

# 鸿坤 sso配置
hk-sso:
  url: http://sso.hongkun.com.cn/login.aspx
  ias:
    id: 40
    key: 706A1DBF4D13497082826F7EF78FF124A08798854C344EFD
#cookie
cookie:
  domain: hongkun.com.cn
  maxAge: 3600000